# Generated by Django 6.0.5 on 2026-05-24 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP (Fuel and Procurement)'), ('UTILITY', 'Utility Data (Electricity)'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='ingestion.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(help_text='The exact JSON or CSV row as parsed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('emission_category', models.CharField(help_text="e.g., 'Stationary Combustion', 'Purchased Electricity', 'Business Travel'", max_length=255)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity_date_end', models.DateField(blank=True, help_text='For periods, e.g., utility bills', null=True)),
                ('normalized_quantity', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPICIOUS', 'Suspicious')], default='PENDING_REVIEW', max_length=20)),
                ('audit_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.ingestionjob')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawdatarecord')),
            ],
        ),
    ]
